window.qq = window.qq || {};
qq.maps = qq.maps || {};
window.soso || (window.soso = qq);
soso.maps || (soso.maps = qq.maps);
(function () {
    function getScript(src) {
        document.write('<' + 'script src="' + src + '"' +' type="text/javascript"><' + '/script>');
    }
    qq.maps.__load = function (apiLoad) {
        delete qq.maps.__load;
        apiLoad([["2.4.38","",0],["http://open.map.qq.com/","apifiles/2/4/38/mods/","http://open.map.qq.com/apifiles/2/4/38/theme/",true],[1,18,34.519469,104.461761,4],[1479979905345,"http://pr.map.qq.com/pingd","http://pr.map.qq.com/pingd"],["http://apis.map.qq.com/jsapi","http://apikey.map.qq.com/mkey/index.php/mkey/check","http://sv.map.qq.com/xf","http://sv.map.qq.com/boundinfo","http://sv.map.qq.com/rarp","http://search.map.qq.com/","http://routes.map.qq.com/","http://confinfo.map.qq.com/confinfo"],[[null,["http://rt0.map.gtimg.com/tile","http://rt1.map.gtimg.com/tile","http://rt2.map.gtimg.com/tile","http://rt3.map.gtimg.com/tile"],"png",[256,256],1,19,"114",true,false],[null,["http://m0.map.gtimg.com/hwap","http://m1.map.gtimg.com/hwap","http://m2.map.gtimg.com/hwap","http://m3.map.gtimg.com/hwap"],"png",[128,128],4,18,"110",false,false],[null,["http://p0.map.gtimg.com/sateTiles","http://p1.map.gtimg.com/sateTiles","http://p2.map.gtimg.com/sateTiles","http://p3.map.gtimg.com/sateTiles"],"jpg",[256,256],1,19,"101",false,false],[null,["http://rt0.map.gtimg.com/tile","http://rt1.map.gtimg.com/tile","http://rt2.map.gtimg.com/tile","http://rt3.map.gtimg.com/tile"],"png",[256,256],1,19,"",false,false],[null,["http://sv0.map.qq.com/hlrender/","http://sv1.map.qq.com/hlrender/","http://sv2.map.qq.com/hlrender/","http://sv3.map.qq.com/hlrender/"],"png",[256,256],1,19,"",false,false],[null,["http://rtt2.map.qq.com/rtt/","http://rtt2a.map.qq.com/rtt/","http://rtt2b.map.qq.com/rtt/","http://rtt2c.map.qq.com/rtt/"],"png",[256,256],1,19,"",false,false],null,[["http://rt0.map.gtimg.com/vector/","http://rt1.map.gtimg.com/vector/","http://rt2.map.gtimg.com/vector/","http://rt3.map.gtimg.com/vector/"],[256,256],4,18,"114",["http://rt0.map.gtimg.com/icons/","http://rt1.map.gtimg.com/icons/","http://rt2.map.gtimg.com/icons/","http://rt3.map.gtimg.com/icons/"]],null],["http://s.map.qq.com/TPano/v1.1.1/TPano.js","http://map.qq.com/",""]],loadScriptTime);
    };
    var loadScriptTime = (new Date).getTime();
    getScript("http://open.map.qq.com/apifiles/2/4/38/main.js");
})();

(function($){$.fn.kxbdSuperMarquee=function(options){var opts=$.extend({},$.fn.kxbdSuperMarquee.defaults,options);return this.each(function(){var $marquee=$(this);var _scrollObj=$marquee.get(0);var scrollW=$marquee.width();var scrollH=$marquee.height();var $element=$marquee.children();var $kids=$element.children();var scrollSize=0;var _type=(opts.direction=='left'||opts.direction=='right')?1:0;var scrollId,rollId,isMove,marqueeId;var t,b,c,d,e;var _size,_len;var $nav,$navBtns;var arrPos=[];var numView=0;var numRoll=0;var numMoved=0;$element.css(_type?'width':'height',10000);var navHtml='<ul>';if(opts.isEqual){_size=$kids[_type?'outerWidth':'outerHeight']();_len=$kids.length;scrollSize=_size*_len;for(var i=0;i<_len;i++){arrPos.push(i*_size);navHtml+='<li>'+(i+1)+'</li>';}}else{$kids.each(function(i){arrPos.push(scrollSize);scrollSize+=$(this)[_type?'outerWidth':'outerHeight']();navHtml+='<li>'+(i+1)+'</li>';});}
navHtml+='</ul>';if(scrollSize<(_type?scrollW:scrollH))return;$element.append($kids.clone()).css(_type?'width':'height',scrollSize*2);if(opts.navId){$nav=$(opts.navId).append(navHtml).hover(stop,start);$navBtns=$('li',$nav);$navBtns.each(function(i){$(this).bind(opts.eventNav,function(){if(isMove)return;if(numView==i)return;rollFunc(arrPos[i]);$navBtns.eq(numView).removeClass('navOn');numView=i;$(this).addClass('navOn');});});$navBtns.eq(numView).addClass('navOn');}
if(opts.direction=='right'||opts.direction=='down'){_scrollObj[_type?'scrollLeft':'scrollTop']=scrollSize;}else{_scrollObj[_type?'scrollLeft':'scrollTop']=0;}
if(opts.isMarquee){marqueeId=setTimeout(scrollFunc,opts.scrollDelay);$marquee.hover(function(){clearInterval(marqueeId);},function(){clearInterval(marqueeId);marqueeId=setTimeout(scrollFunc,opts.scrollDelay);});if(opts.controlBtn){$.each(opts.controlBtn,function(i,val){$(val).bind(opts.eventA,function(){opts.direction=i;opts.oldAmount=opts.scrollAmount;opts.scrollAmount=opts.newAmount;}).bind(opts.eventB,function(){opts.scrollAmount=opts.oldAmount;});});}}else{if(opts.isAuto){start();$marquee.hover(stop,start);}
if(opts.btnGo){$.each(opts.btnGo,function(i,val){$(val).bind(opts.eventGo,function(){if(isMove==true)return;opts.direction=i;rollFunc();if(opts.isAuto){stop();start();}});});}}
function scrollFunc(){var _dir=(opts.direction=='left'||opts.direction=='right')?'scrollLeft':'scrollTop';if(opts.isMarquee){if(opts.loop>0){numMoved+=opts.scrollAmount;if(numMoved>scrollSize*opts.loop){_scrollObj[_dir]=0;return clearInterval(marqueeId);}}
var newPos=_scrollObj[_dir]+(opts.direction=='left'||opts.direction=='up'?1:-1)*opts.scrollAmount;}else{if(opts.duration){if(t++<d){isMove=true;var newPos=Math.ceil(easeOutQuad(t,b,c,d));if(t==d){newPos=e;}}else{newPos=e;clearInterval(scrollId);isMove=false;return;}}else{var newPos=e;clearInterval(scrollId);}}
if(opts.direction=='left'||opts.direction=='up'){if(newPos>=scrollSize){newPos-=scrollSize;}}else{if(newPos<=0){newPos+=scrollSize;}}
_scrollObj[_dir]=newPos;if(opts.isMarquee){marqueeId=setTimeout(scrollFunc,opts.scrollDelay);}else if(t<d){if(scrollId)clearTimeout(scrollId);scrollId=setTimeout(scrollFunc,opts.scrollDelay);}else{isMove=false;}};function rollFunc(pPos){isMove=true;var _dir=(opts.direction=='left'||opts.direction=='right')?'scrollLeft':'scrollTop';var _neg=opts.direction=='left'||opts.direction=='up'?1:-1;numRoll=numRoll+_neg;if(pPos==undefined&&opts.navId){$navBtns.eq(numView).removeClass('navOn');numView+=_neg;if(numView>=_len){numView=0;}else if(numView<0){numView=_len-1;}
$navBtns.eq(numView).addClass('navOn');numRoll=numView;}
var _temp=numRoll<0?scrollSize:0;t=0;b=_scrollObj[_dir];e=(pPos!=undefined)?pPos:_temp+(opts.distance*numRoll)%scrollSize;if(_neg==1){if(e>b){c=e-b;}else{c=e+scrollSize-b;}}else{if(e>b){c=e-scrollSize-b;}else{c=e-b;}}
d=opts.duration;if(scrollId)clearTimeout(scrollId);scrollId=setTimeout(scrollFunc,opts.scrollDelay);}
function start(){rollId=setInterval(function(){rollFunc();},opts.time*1000);}
function stop(){clearInterval(rollId);}
function easeOutQuad(t,b,c,d){return-c*(t/=d)*(t-2)+b;}
function easeOutQuint(t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;}});};$.fn.kxbdSuperMarquee.defaults={isMarquee:false,isEqual:true,loop:0,newAmount:3,eventA:'mousedown',eventB:'mouseup',isAuto:true,time:5,duration:50,eventGo:'click',direction:'left',scrollAmount:1,scrollDelay:10,eventNav:'click'};$.fn.kxbdSuperMarquee.setDefaults=function(settings){$.extend($.fn.kxbdSuperMarquee.defaults,settings);};})(jQuery);
$(function(){var sw=0;$(".banner_choose li").mouseover(function(){sw=$(".banner_choose li").index(this);myShow(sw);});function myShow(i){$(".banner_choose li").eq(i).addClass("choose_now").siblings("li").removeClass("choose_now");$(".banner_pic a").eq(i).stop(true,true).css("display","block").siblings("a").hide();}
$(".banner_pic").hover(function(){if(myTime){clearInterval(myTime);}},function(){myTime=setInterval(function(){myShow(sw)
sw++;if(sw==($(".banner_pic").children().length)){sw=0;}},5000);});$(".icon-bannerleft").click(function(){sw=$(".choose_now").index()-1;if(sw==-1){sw=($(".banner_pic").children().length-1)}
myShow(sw);});$(".icon-bannerright").click(function(){sw=$(".choose_now").index()+1;if(sw==$(".banner_pic").children().length){sw=0}
myShow(sw);});var myTime=setInterval(function(){myShow(sw)
sw++;if(sw==($(".banner_pic").children().length)){sw=0;}},5000);});$(function(){$('.student_list_m').kxbdSuperMarquee({time:999999,distance:245,btnGo:{right:'.student_list_left',left:'.student_list_right'},direction:'left'});$('.teacher_list_m').kxbdSuperMarquee({time:999999,distance:245,btnGo:{right:'.teacher_list_left',left:'.teacher_list_right'},direction:'left'});$(".display_list_word span").mouseenter(function(){$(this).addClass("active").siblings().removeClass("active");num=$(this).index();if(num==1){$(".student_list").show();$(".teacher_list").hide();}else{$(".student_list").hide();$(".teacher_list").show();}})
$(".display_list_word2 span").mouseenter(function(){$(this).addClass("active").siblings().removeClass("active");num=$(this).index();if(num==1){$(".ielts_list").hide();$(".tolef_list").show();}else{$(".ielts_list").show();$(".tolef_list").hide();}})
if(navigator.userAgent.indexOf("Mac OS X")>0){$(".index_main .index_main_right .web_service ul li").css("height","56px");$(".student_list ul li h5").css("padding","5px 0");$(".student_list ul li h4").css("padding","5px 0");}
$(".shade").height($(document).height());$("#bigmap").height($(window).height()-40);$(".icon-closebutton").click(function(){$(".shade").hide();$(".bigmap").hide();})});$(window).resize(function(){$(".shade").height($(document).height());$("#bigmap").height($(window).height()-40);});function init(a1,a2,a3){var center=new qq.maps.LatLng(a2,a3);var map1=new qq.maps.Map(a1,{center:center,zoom:16});var marker=new qq.maps.Marker({position:center,animation:qq.maps.MarkerAnimation.DROP,map:map1});}
function initbig(a2,a3){$(".shade").show();$(".bigmap").show();var center=new qq.maps.LatLng(a2,a3);var map999=new qq.maps.Map(document.getElementById('bigmap'),{center:center,zoom:16});var marker=new qq.maps.Marker({position:center,animation:qq.maps.MarkerAnimation.DROP,map:map999});}
$(function(){$(".index_main_list li").hover(function(){$(this).children("div").css("top","0");bHeight=$(this).children("div").height();sHeight=$(window).height();fHeight=$(this).offset().top;abc=$(document).scrollTop();aaaaaa=abc+sHeight-40;bbbbbb=fHeight+bHeight;if(bHeight>sHeight){dddd=fHeight-abc;dddd=0-dddd;$(this).children("div").css("top",dddd);}else if(bbbbbb>aaaaaa){cccc=bbbbbb-aaaaaa;cccc=0-cccc;$(this).children("div").css("top",cccc);}
$(this).children("div").show();},function(){$(this).children("div").hide();})})
//@ sourceMappingURL=100yy.map